### ISSUE TITLE
Language Styleguide

### ISSUE THREAD

**Issue by Charlotteis** [hoodiehq/editorial#1]
## The Issue
Language is a powerful tool, and it is very easy to wield it badly. In order to be the best Hoodies we can be, lets outline from the start the language we should and shouldn't be using.

## The Solution

Create a README or Wiki (thanks @renrutnnej) that acts as a 'Language Styleguide' where we list all the Dos and Don'ts. Topics like pronouns, the attitude and discourse of "Hoodie", how to talk about folk with disabilities (i.e not "The Disabled", but "people with disabilities").

## When the issue is considered complete

This will be an ongoing process, so lets consider this complete when we have the Wiki set up and our first draft of guidelines?

**Comment by renrutnnej** [comment]
I've used the wiki feature before as a living style guide and it was really useful for updating and redefinining :)

**Comment by Charlotteis** [comment]
@renrutnnej ooooooooo good idea. We can totes start a wiki on this repo, does that sound sensible?

**Comment by janl** [comment]
I like the wiki idea

**Comment by schisepo** [comment]
The wiki idea sounds great. I definitely have a lot to learn in this area...

**Comment by bnb** [comment]
So I've worked on something similar to this for nodejs/evangelism. It might be a good place to start and get ideas: [link](https://github.com/nodejs/evangelism/blob/master/documents/socialMedia.styleGuide.md). You could copy and paste the whole thing, or just take concepts you think may be helpful from it and apply them here.

**Comment by Charlotteis** [comment]
That looks cool. I'd rather start from scratch but we can certainly study those guidelines :)
If anyone would like to start a Wiki on this (@renrutnnej and others?) then just let us know you are doing it :tada:

**Comment by skeskali** [comment]
I'd like to contribute to something like this.

**Comment by Web-Dev-Rich** [comment]
🙋I am _bursting_ to do something editorial. Is it OK if I setup the wiki? I'll use the sections from the link from @bnb as a starting point. I can do it this evening (GMT).

**Comment by bnb** [comment]
@Web-dev-rich Go for it! I'd be happy to review when possible.

**Comment by Web-Dev-Rich** [comment]
Hey all I've had time to do so far is a list of headings for the wiki. Is this the kind of thing ppl are looking for?

**Comment by renrutnnej** [comment]
Thanks @Web-Dev-Rich!

I moved the style guide to its own page so that we can utilize the wiki for other guides, resources and docs.

**Comment by Charlotteis** [comment]
Good job so far @Web-Dev-Rich & @renrutnnej. I appreciate your efforts!

**Comment by renrutnnej** [comment]
Okay I've added some initial contributions to the guide (which you can see [here](https://github.com/hoodiehq/editorial/wiki/Hoodie-Language-Style-Guide), so I think we've successfully created our first draft 🎉

**Comment by bnb** [comment]
@renrutnnej Wow, that's awesome! I'll start writing on that ASAP.

**Comment by janl** [comment]
This is fantastic! <3

Process question: should we keep this open until most of the placeholders are filled out, or should we close these and open individual issues for each placeholder (or group of placeholders)?

On the one hand: smaller scoped issues might attract more people to contribute vs. many open issues might turn people off.

**Comment by renrutnnej** [comment]
I think it'd be suitable to close this now that it's been started @janl, so I'm going to do that now. 

And to answer your question I think individual issues would be the most appropriate for further additions. :D
