### ISSUE TITLE
Determine Content Ownership/Licensing

### ISSUE THREAD

**Issue by remixz** [hoodiehq/editorial#10]
## The Issue

Since we'll (hopefully!) have many people submitting work for the Hoodie website, we need to determine who owns the content they submit, and how it should be licensed. This needs to apply to written work, as well as any illustrations, photographs, or any other original work submitted for inclusion the Hoodie website.

## The Solution

Create a document on content ownership and licensing. My suggestion is that the author of the content owns the work, so they can post it on their own websites, but we ask it be licensed under [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). This fosters the sense of openness in the community, and that by building upon others' work, we can create something even better.

## When the issue is considered complete

When we have documented in this repository who owns submitted content of any kind, and under what license we either recommend, or require, depending on the content.

**Comment by Charlotteis** [comment]
So this repo (editorial) has an MIT License.
Many people have written for the Hood.ie blog before but I don't know if we have Licensing. Hopefully @janl could answer that question.

I'm not sure if I feel comfortable with any licensing on someones work. If I write for Hoodie, I would probably ask someone if I can put it on my own blog but I don't really want my own content to have rules? I'm the one who produced it after all.

As with most things, I am usually easily turned around on this. But seeing as I doubt me hosting a blogpost on Hoodie elsewhere will really damage or cost the Hoodie community... I'm really not sure if we need to be strict like this.

**Comment by bnb** [comment]
@charlotteis Licensing should be mandatory - there is no reason we shouldn't require an open licence. 

As a freelance writer, I understand that you might want to post the content you write on your own blog, but doing that undermines the content on the official blog. Duplicate content is _very_ bad for SEO and robot crawling. If someone writes a blog postfor the Hoodie site, it needs to be exclusive - they're writing it for us, and exclusivity is part of the deal.

**Comment by Charlotteis** [comment]
I think I'm put off by it because the description of the license on the website was quite cold. I'm also a bleeding heart and care more that everyone has full rights to their content, than Hoodies SEO but that probably means my arguments aren't as valid :D.

Would you feel more comfortable with official license, or would "Ask permission before you put the content you write for us, elsewhere" written somewhere sufficient?

My next question: If we do have a license (and I am not completely against it), how do we enforce it? Say you write something then copy it to your blog, you've now broken the terms of the license. What does someone enforcing the license need to do next (if asking you nicely not to do that doesn't work)?

Great discussions as always :sparkling_heart:.

**Comment by remixz** [comment]
I'm not sure if I'd feel comfortable requiring someone's post to be exclusive when we're asking them to do it for free. If at some point we're able to pay a writer for their post, then sure, it should definitely be exclusive. However, we should be giving the writer rights to their writing when it's done for free, so they can get the full value out of it. 

To be honest, I don't think many people would go shopping their post around at every site. I think at most, people would post a copy of it on their own website, and likely link back to the Hoodie blog. SEO-wise, we wouldn't be punished, since we'd be the original publisher, and be the first copy that a search engine indexed. If the writer posts it to their own blog, they can mitigate any SEO punishment by adding a `<link rel="canonical">` tag, linking to the Hoodie blog. In any case, though, it's unlikely there would be any SEO punishment at all. Search engines are pretty smart about this, and mostly punish duplicate content on obviously-scraped sites. See: https://support.google.com/webmasters/answer/66359?hl=en. Specifically:

> Duplicate content on a site is not grounds for action on that site unless it appears that the intent of the duplicate content is to be deceptive and manipulate search engine results. If your site suffers from duplicate content issues, and you don't follow the advice listed above, we do a good job of choosing a version of the content to show in our search results.

@Charlotteis If we had an exclusivity license, and the writer broke that agreement, it'd become a legal issue. Depending on who hosts it, and where it's hosted, there's a variety of legal procedures. The gist of any of the procedures is proving that the Hoodie project owns the content, and that its publishing on another site breaks our exclusivity of that content. This would be harder to enforce unless we had a written agreement that the writer signed, which I feel is a lot of bureaucracy for something we're asking someone to do for free.

**Comment by bnb** [comment]
I think we should have a license that is a part of contrbuti going an article. We are an open-source project, and we should likewise have an open-source license for our content. 

I by no means think we should claim complete exclusivity on content people publish under the Hoodie umbrella, to the point where we're witch hunting people who use the content

My thoughts on licensing are essentially synonymous with how a typical OSS project is licensed. People are free to use the content in a way that they see fit, using the document under fair use. 

The main restriction I think needs to be enforced is pulling the article as a carbon copy and publishing it somewhere else. Just as you can't duplicate a piece of software's code, paste your name on it, and sell it for cheaper, you shouldn't be able to cut something from the blog and publish it externally. It was written as a property of the blog, with the author fully aware of this condition.

As for the action of enforcement, it can be handled like any other digital property: ask kindly first, and escalate to contacting the host and then send a takedown notice. It's not different than any other software's license.

**Comment by bnb** [comment]
@remixz: thanks for the that point!

The only two catches I see with your suggestion are:

* Is it acceptable to assume that all writers will be able to add the canonical tag on their site to a specific blog post? I'm not sure of a way to do that in, say, Ghost without having to edit the templates with an if statement that will run on every post
* I haven't done much SEO, so I'd like to ask how we can be sure our post will be indexed first and the author's second? 

Again, thanks for bringing real SEO and licensing knowledge to the table!

**Comment by remixz** [comment]
> Is it acceptable to assume that all writers will be able to add the canonical tag on their site to a specific blog post? I'm not sure of a way to do that in, say, Ghost without having to edit the templates with an if statement that will run on every post.

Fair point. Probably will be impossible for every writer to add it themselves. My feeling is that most writers would add the post to their own site more as a portfolio builder, rather than trying to get more views to their blog. 

> I haven't done much SEO, so I'd like to ask how we can be sure our post will be indexed first and the author's second?

So, the thing about SEO is that it's really something that isn't easily predictable. :smile: There are do's and do-not's, but ultimately there are so many different algorithms behind search engines that there's no sure-fire way that we'll always be first. However, we're more likely to be, since the Hoodie site has existed for a while, has published lots of content that's been indexed before, and likely gets a decent amount of people searching for it. Additionally, search engines like Google serve different results to different people based on their search history and all of the other fun analytics they have. 

To put it briefly: we can't guarantee we'll be first, but since we'll be the first site that puts a post online (even if by minutes), and we already have lots of indexed content, we're more likely to be first.

**Comment by bnb** [comment]
I'm not going to push for exclusivity any more - it seems the general consensus is against it. So, are there caveats we need to consider?

**Comment by janl** [comment]
Great discussion here, sorry for coming in late.

I’m very versed in open source licenses and and CC-BY-SA-4.0 is a great suggestion. One addition might be NC (non commercial), it means, our blog posts can’t be re-blogged with ads, which I think is a good idea, but I’m happy to go with group consensus on this one (the original author will still be able to do whatever they want).

Other than than, let’s get this written up and put into our procedures. At least https://github.com/hoodiehq/editorial/blob/master/CONTRIBUTING.md should cover this, so people know what they are getting into early on.

**Comment by Charlotteis** [comment]
I'm happy for this to go ahead. You've brought some really good things to the table here @bnb, would you be happy with CC-BY-SA-4.0? I'm fine with the NC part too, in the spirit of Open Source.

I'd also like to apologise for my lack of knowledge in this area, reading through this again I can totally see why Licensing is important, it's another way we can respect our authors and creators and the work they do :)

**Comment by renrutnnej** [comment]
Are we still thinking to include the NC language? I don't know that we have anything currently written about editorial ownership. 

I'm trying to figure out if this issue is still relevant or if we were getting a bit ahead of ourselves at the time.

**Comment by renrutnnej** [comment]
Closing per the 72 hour window passing without response. I don't believe this is currently an issue for the editorial team.
