### ISSUE TITLE
Add GitHub Integrations to Slack

### ISSUE THREAD

**Issue by Charlotteis** [hoodiehq/editorial#17]
## The Issue

Those not used to checking their GitHub notifications may miss a lot of what happens on GitHub until its too late. And many may miss the suggested 72-hour window for commenting on new process suggestions before they are accepted.

## The Solution

Add a GitHub integration to the editorial Slack channel linked to the editorial repository.

## When the issue is considered complete

Everyone in the editorial channel can see when a new Issue is created, when a new PR is created. Maybe when a new comment is made too but perhaps that will make the channel too busy?

**Comment by bnb** [comment]
Adding a GitHub integration to Slack should be fine, even with notifications for comments. If it's too much we can crank it down a notch as many times as needed until we get the right balance.

**Comment by Charlotteis** [comment]
Sounds good to me @bnb, thanks for your input! I don't think I have Admin on the channel, is this something you are able to do @janl?

**Comment by renrutnnej** [comment]
:+1:  (minus comment notifications)

**Comment by janl** [comment]
Done: https://github.com/hoodiehq/editorial/issues/45

Notifications for PRs, Issues and git pushes, but not individual comments on issues.

Let me know if this should be tweaked.
