### ISSUE TITLE
Add methods of contacting people privately

### ISSUE THREAD

**Issue by Charlotteis** [hoodiehq/editorial#18]
## The Issue

Not everyone feels able to talk in the open about what they want to, or feel able to challenge things publicly.

## The Solution

Add a paragraph to the README and/or CONTRIBUTING to show people who they can contact privately should they need to. Point out that you can privately DM on Slack, but also private email addresses if possible. 

As the team is in its infancy, I think myself and Jan should be the points of contact.

## When the issue is considered complete

It is clear in a document who can be contacted privately (and how) should the need arise.

**Comment by Charlotteis** [comment]
We've added a contact template, just waiting on some more stuff to happen before Jan and I can add ourselves to the template.

**Comment by janl** [comment]
other stuff: check

**Comment by Charlotteis** [comment]
Ace, thanks Jan. Will PR this up tomorrow.

**Comment by renrutnnej** [comment]
Closing this since contacts were added. :+1:
