### ISSUE TITLE
BLOG: Post on the Editorial Team

### ISSUE THREAD

**Issue by Charlotteis** [hoodiehq/editorial#3]
## The Proposal

Let's write a blog post on our editorial team, to share the good news that we now exist! Officially started on the 21st of November with an awesome Google Hangout full of people. Talk about what our goal is, how we're going to start the process (documentation, meetings, slack) and what areas we are going to cover. Talk about how we want more people and ask for one-off ideas?

**Comment by bnb** [comment]
I can pick this up, but I'm currently phone-only, as my computer is handicapped right now. If someone else gets to this before I get a new computer, feel free to take it over - if not, I'll get it done ASAP.

**Comment by bnb** [comment]
Hey, I'm available to take this one over now. Any input on content?

**Comment by Charlotteis** [comment]
Just a few ideas:

1. What the team is
2. How it started (i think someone should have a pic of the google hangout? i tried to find one on my computer, but no luck :()
3. Where you can find us
4. Examples of our work so far and open discussions we are having
5. How you can contribute

**Comment by renrutnnej** [comment]
Hi folks, just finished a rough draft of this post. Needs feedback here: https://docs.google.com/document/d/1TsI7Cwe-IKgoVz2u4f-V0RWVWHKSun6K0SXpRx52L-U/edit?usp=sharing

**Comment by gr2m** [comment]
love it :clap:

**Comment by renrutnnej** [comment]
Closing per this post going live today: http://hood.ie/blog/shaping-an-open-source-editorial-team.html
