### ISSUE TITLE
How to submit animals?

### ISSUE THREAD

**Issue by lewiscowper** [hoodiehq/editorial#36]
We have no documentation on how to submit animals to the tumblr. We should add that. :)

**Comment by gr2m** [comment]
We activated the "submit a post" feature on http://meetthehoodies.tumblr.com/, so everyone can submit suggestions now

**Comment by nolanlawson** [comment]
Can we have a green kangaroo to celebrate the partnership between Hoodie and Pouch? :smiley:

**Comment by gr2m** [comment]
@nolanlawson <3

**Comment by Charlotteis** [comment]
We still need to create the readme for this ("Submit a post to this tumblr (link)") in an .md somewhere in this repo. A nice small task.

**Comment by lewiscowper** [comment]
I can take this.
