### ISSUE TITLE
Contributing to the editorial repo

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#39]
I can't remember if I saw discussion on this in Slack or not, but have we determined criteria for closing issues and pull requests?

I know there's a method for contributing to the Hoodie project outlined in the CONTRIBUTING doc [here](https://github.com/hoodiehq/hoodie/blob/master/CONTRIBUTING.md#pull-requests) for the primary Hoodie repo so I'm proposing that we use that to start. 

Barring any objection in the next 72 hours, which I recall being an appropriate amount of time for issues to breath :relaxed:, I'm going to begin working through the repo.

**Comment by Charlotteis** [comment]
What do you mean by "working through the repo"? :)

**Comment by renrutnnej** [comment]
Oops, that was vague. 

I meant that there are some things that could be pushed forward or closed at this point, but I'm unsure if we've determined the method for that. I'm available to help do so, but I wanted to follow the appropriate route.

**Comment by Charlotteis** [comment]
We discussed this in Slack, but just to sync all info: Yes, ok!

**Comment by Charlotteis** [comment]
@renrutnnej Jan and I have gone through a lot of issues and closed what needs to be closed, merged what needed to be merged. Was there anything you want to see come out of this issue in particular, did we need to write process anywhere? Or can we close? :sparkles:

**Comment by renrutnnej** [comment]
We can totally just close it :)
