### ISSUE TITLE
Status Update?

### ISSUE THREAD

**Issue by bnb** [hoodiehq/editorial#41]
Hello again, everybody.

I just wanted to see what the status of this project was, and where it is going to go from here. It seems to have majorly died down in the past month with lots of open-ended Issues and PRs. Are we still going to actively develop the editorial side of Hoodie? If so, who is going to continue contributing from now on, after the original publicity has faded?

**Comment by Charlotteis** [comment]
I know @renrutnnej was intending to do some stuff with all the open PRs.
I'm waiting on a few things from @janl to do some stuff (whereever I've mentioned their name in a PR or Issue on this repo)
I've started my "interview with Hoodie" thing. I know my Pull Request guide is still unfinished but it takes a lot of work.

I know it must be discouraging, but we only asked people to contribute an hour here or there. And everyone is doing it for free. It's also December and we're right up against the holiday period so it wasn't the best time to start the Editorial team. Hopefully in the new year it will become more active. But if folk don't want to continue on with the team, that is totally fine and we can encourage new people to take part.

I firmly believe that the Editorial team is just getting started, whichever form it ends up taking :)

**Comment by Charlotteis** [comment]
I have gone through all of the PRs and cleared everything out.

**Comment by janl** [comment]
@bnb Heya, thanks for checking in. I’m not sure what your other experiences in open source are, but as far as I can tell from my humble experience, we have made tremendous progress for the few weeks that this has been a thing.

Like @Charlotteis said, it is the end of the year and everyone is doubly busy and we still get things moving forward.

Everyone, don’t be discouraged by this, we all do what we can and we are moving forward, that’s all that counts :)

Keep up the good work and enjoy the holidays!

**Comment by bnb** [comment]
@janl Okay, really happy to hear that. I just took a look at the repo for the first time in a while, and it seemed like all the issues/comments in them were 20+ days old. I didn't, however, look at newly closed issues. 

Awesome to see that we're still kicking. I'll start doing work where I can.

**Comment by Charlotteis** [comment]
Think I will close this in the hopes that @bnb is sufficiently updated and if not, will be soon :)
