### ISSUE TITLE
blog post suggestion: meet the hoodies, in person edition

### ISSUE THREAD

**Issue by janl** [hoodiehq/editorial#44]
@gr2m should write up his experiences with running two Your First PR / Hoodie hands-on workshops in New York.

@gr2m: I know you don’t consider yourself a strong writer and I’m more than happy to help, maybe you can start with an outline, and a few paraphrased bullet points per paragraph and I turn it into prose?

**Comment by Charlotteis** [comment]
I would love to see this written, and am happy to help too.

**Comment by gr2m** [comment]
Thanks you two, I love the idea to write about it, I’ll give it some thoughts this week :)

**Comment by gr2m** [comment]
done via http://hood.ie/blog/meet-the-hoodies-offline.html
