### ISSUE TITLE
Meet the Hoodies Readme

### ISSUE THREAD

**Issue by Charlotteis** [hoodiehq/editorial#50]
# The Problem

We have no file to read to show us how to do a Meet the Hoodies interview.

# The Solution

Write a document in this repo, telling team members how they can do a 'Meet the Hoodies' blog post like #40. Covering the picking, the writing, the reviewing, the publishing.

Interview questions are:

```
1. What's your favorite animal?

2. What's your role / what have you contributed to Hoodie?

3. What's your favorite use of Hoodie in the wild?

4. What in your opinion makes the Hoodie project unique and interesting?

5. What advice do you have for aspiring Hoodie contributors?
```

**Comment by janl** [comment]
on it.

**Comment by janl** [comment]
PR here: https://github.com/hoodiehq/editorial/pull/51
