### ISSUE TITLE
Meet The Hoodies: Jenn

### ISSUE THREAD

**Issue by janl** [hoodiehq/editorial#52]
As per https://github.com/hoodiehq/editorial/blob/master/documents/blog-post-types/meet-the-hoodies.md

I’m nominating  @renrutnnej :) 

Here are your questions!

1. What's your favorite animal?

2. What's your role / what have you contributed to Hoodie?

3. What's your favorite use of Hoodie in the wild?

4. What in your opinion makes the Hoodie project unique and interesting?

5. What advice do you have for aspiring Hoodie contributors?

**Comment by schisepo** [comment]
Thanks for taking this up ☺☺☺ I'm away from reliable connectivity at the
moment.

**Comment by janl** [comment]
@schisepo you’re very welcome! :)

**Comment by renrutnnej** [comment]
I'm working on this today!

**Comment by Charlotteis** [comment]
@renrutnnej these responses are great :)
Does anyone else want to review this or help get this on to the website?
If no-one takes this up in the next couple of days I'll do it myself, though would love it if someone else could learn how to do it to see if the process works for them :)

**Comment by Charlotteis** [comment]
Have turned your notes into a markdown file everyone can review at #53

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/editorial/pull/53
