### ISSUE TITLE
Post Proposal: Meet the Hoodies

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/editorial#54]
> What is your blog post about? Describe it in about one paragraph.

Our first 4 "Meet the Hoodies" events in NYC, Berlin and Frankfurt: 
https://ti.to/hoodie/

> Approximately how long do you think the post will be?

2000 characters?

> Approximately how long do you think it will take you to write this post?

I have a draft already:
https://docs.google.com/a/martynus.net/document/d/16h0c2NDfPn_PFZc_UoXgoHk8ZZkhcC7N2lzuqucp93w/edit?usp=sharing – please edit away <3

> Do you think your post could make use of any illustrations or photographs?

Yes, I uploaded them to flickr:
https://www.flickr.com/photos/116240988@N08/sets/72157664073558051

> Do you have any links to previous writing?

not really :(

> Where else can we find you on the internet? (e.g. your blog, Tumblr, Medium, Twitter, etc.)

- https://twitter.com/gr2m/
- https://github.com/gr2m/

> Anything else you want to tell us?

:bouquet: to all the wonderful Hoodie editorial humans 

Please feel free to put my draft upside down, I’m looking forward to learn from your changes :)

**Comment by janl** [comment]
Excellent @gr2m! — I’ve left a few minor notes. If we can get this into shape, I’d love to post it this week :)

**Comment by gr2m** [comment]
here is the PR to the website:
https://github.com/hoodiehq/hood.ie/pull/226

So I guess I can close this?
