### ISSUE TITLE
Remove blog-post drafts from Editorial repo

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#59]
Hello Editorialites ✨

I would like to suggest that we make the contribution process a tad clearer and more accessible for folks to jump in on.

Right now as it stands, the process to get something on the blog from suggestion to publication looks like this:
- Suggest blog post topic in `hoodiehq/editorial` issues
- Upon approval author creates text in their preferred format
- Text is formatted into markdown file that goes to `hoodiehq/editorial/blog-posts`
- Markdown file gets copied into `hoodiehq/hood.ie/_drafts
- Markdown file gets reviewed and converted to `hoodiehq/hood.ie_/posts`
- Markdown file gets pushed to master and published live :tada:

I would like to suggest that we eliminate the double work of having a `hoodiehq/editorial/blog-posts` file in this repo and make follow this process:

- Suggest blog post topic in `hoodiehq/editorial` issues
- After person claims issue they follow the process outlined in `hoodiehq/hood.ie` README: https://github.com/hoodiehq/hood.ie#blog

I know there are plans to create an in-depth "How to" guide and I am not suggesting we skip that, I encourage that effort as a means to make the process clearer.

I do think we should streamline the process in general.

**Comment by Charlotteis** [comment]
:+1: 
lets get rid of everything in blog-posts

**Comment by janl** [comment]
+1

**Comment by gr2m** [comment]
yeah, :100: for streamlining :)

**Comment by renrutnnej** [comment]
I deleted the folder and tweaked the [README](https://github.com/hoodiehq/editorial/commit/5711486b5c57eb4cc3fdf3b98616c5f16511a01a) for the time being. I need to review the files in `/documents` to get some clarity on process decisions there. 

My intent for now is to point people to a stream lined process so they feel empowered to contribute right away, instead of being confused by the disconnectedness of our documentation right now.
