### ISSUE TITLE
Update twitter.com/hoodiehq background image

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/editorial#60]
### :dart: The goal

the current background banner image is a bit outdated:

![hoodiehq-banner](https://cloud.githubusercontent.com/assets/39992/13408697/21348142-defd-11e5-8e29-d4db086a2fb3.png)

We would like to replace at least the image on the right side with [one or two images from our Meet the Hoodies events](https://www.flickr.com/photos/116240988@N08/sets/72157664073558051), which show that we are more than young white boys hacking on a couch :)

### :clipboard: Step by Step

- [x] claim this issue (@girvo)
- [x] take [the background image](https://cloud.githubusercontent.com/assets/39992/13408697/21348142-defd-11e5-8e29-d4db086a2fb3.png), replace the couch image on the right with one or two images from one of these: https://www.flickr.com/photos/116240988@N08/sets/72157664073558051
- [x] comment below if the final image, we will put it in :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by girvo** [comment]
![new-hoodie-bkg](https://cloud.githubusercontent.com/assets/1305443/13422149/85cf3b10-dfde-11e5-8213-9d450d938bba.png)

I took a swing at it, figured it was worth a shot, though feel free to use someone elses effort: I'm certainly no graphic designer, just a developer with a Sketch license :+1:

**Comment by gr2m** [comment]
I think it’s great :) I’ll put that in, but if anyone would like to make an alternative suggestion, comment below :)

**Comment by renrutnnej** [comment]
Thanks Josh! This looks great ☺️
