### ISSUE TITLE
BLOG: The return of TGIF!

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#62]
Check out the [TGIF doc here](https://github.com/hoodiehq/editorial/blob/master/documents/TGIF.md).

We need contributors to help curate this weekly blog post of a fun roundup of interesting weekend reads for our Hoodie blog friends.

The time commitment is very minimal and I could see a single contributor doing this once a week (after reviewing the initial template __I bet someone could do the whole thing in an hour__ and I could ensure it gets queued up for publish), or a team of rotating contributors rotating posts could work!

**Comment by gr2m** [comment]
I can be in charge to provide info on what is happening in the code part of the community, like new code contributors, new releases, questions we currently discuss, etc

**Comment by skeskali** [comment]
I'd love to do this!

**Comment by renrutnnej** [comment]
Wooo hoo! @skeskali would you be up to getting one ready for this Friday?

**Comment by skeskali** [comment]
Absolutely!

**Comment by Charlotteis** [comment]
Closing because we did the first return TGIF (good job everyone!), but please reopen it if I shouldn't have!
