### ISSUE TITLE
CONTENT: Write a bio for Blog Bear

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#64]
Part of https://github.com/hoodiehq/hood.ie/issues/234

### :octocat: Starter Issue

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :relaxed:

---

### :pencil2: The Task

In preparation for the Camp Release we are trying to update the hood.ie site. This specific writing task involves adding content to the [Hoodie Animals page](http://hood.ie/animals/) to give readers a better idea of our revolving cast of animal characters. :bear: 

- [x] Claim this issue (@neekyrabbit)
- [ ] Write a bio between 200-400 words long.
- [ ] Submit to @renrutnnej @Charlotteis or @janl for review (Google docs probably work best for this sort of thing)
- [ ] You are done :clap: comment below that your content is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by gr2m** [comment]
As we already shown blog bear on our newsletters, we don’t need to make secret of it, so here it is :)

![blog-bear](https://cloud.githubusercontent.com/assets/39992/13550207/6ceaf098-e2e6-11e5-8883-ba2b4a014169.png)

**Comment by NeekyRabbit** [comment]
Hello - I'd love to write a bio for the Bear. I've never done a pull request before.

**Comment by matsieftw** [comment]
I'd love to write one as well!

**Comment by renrutnnej** [comment]
@NeekyRabbit The blog bear is yours! I'll assign you. I'm Jenn. Please let me know if you have any questions or need any help. 

@matsieftw There's another animal bio issue if you want to check it out: https://github.com/hoodiehq/editorial/issues/66 Comment there if you're interested in taking that on :relaxed: 

Thank you both for responding!

**Comment by NeekyRabbit** [comment]
Hello @renrutnnej I've got a first draft, based on the style of the Docs Chicken, let me know what you think.
 https://docs.google.com/document/d/1gJZnZxTYMRYek54O5xqeLK1NcIDSijTeO17eZ7Tikto/edit?usp=sharing

**Comment by gr2m** [comment]
@NeekyRabbit could you allow for comments to everyone with the link?

PS: You made my day big time I’ve this grin and it doesn't go away, love when that happens 😻🐻

**Comment by janl** [comment]
@NeekyRabbit this is be my favourite thing in the world right now <3333

**Comment by NeekyRabbit** [comment]
Happy to have put a smile on people's faces @gr2m @janl - it should allow comments now.

**Comment by NeekyRabbit** [comment]
I've been in and made a change to the copy @janl based on @gr2m feedback.

**Comment by renrutnnej** [comment]
Thanks @NeekyRabbit! I want to make sure we release Blog Bear's story in the best possible way so I'll keep you posted on how we're going to make that happen :)

**Comment by pawan92** [comment]
hey i would love to help out never contributed to open source project before!

**Comment by renrutnnej** [comment]
Hi @pawan92, this issue is already being worked on, but check out other ones in this repo to see if there's any others that seem interesting :relaxed:

**Comment by renrutnnej** [comment]
I would like to publish an introduction to the blog bear next week on **April 12**.

So that means her bio would go live to both the animals repo, and the blog that day. 

@NeekyRabbit do you have interest in learning how to publish to those areas? I can assist if not. :relaxed:

**Comment by NeekyRabbit** [comment]
@renrutnnej hello - sorry only just picked up your message - been on holiday. Guessing it's all set up now? If not happy to learn how to do it.

**Comment by renrutnnej** [comment]
Closing per https://github.com/hoodiehq/hood.ie/pull/273, thank you @NeekyRabbit!! 👏
