### ISSUE TITLE
CONTENT: Write a bio (and pick out a name) for the development mascot, a beaver

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#65]
Part of https://github.com/hoodiehq/hood.ie/issues/234

### :octocat: Starter Issue

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :relaxed:

---

### :pencil2: The Task

In preparation for the Camp Release we are trying to update the hood.ie site. This specific writing task involves adding content to the [Hoodie Animals page](http://hood.ie/animals/) to give readers a better idea of our revolving cast of animal characters. :dog: 

- [x] Claim this issue (@annaboodle)
- [ ] Write a bio between 200-400 words long.
- [ ] Submit to @renrutnnej @Charlotteis or @janl for review (Google docs probably work best for this sort of thing)
- [ ] You are done :clap: comment below that your content is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by summerspirit** [comment]
Hi @renrutnnej !
Just claiming this one :)

**Comment by renrutnnej** [comment]
Perfect! :relaxed:

**Comment by gr2m** [comment]
Hey @summerspirit, we can send you an image of our Beaver if you like :) Ping us on [Twitter](http://twitter.com/hoodiehq) or in our [Hoodie Chat](http://hood.ie/chat) and we will figure out a way to share it with you, without spoiling the surprise to everyone else :)

**Comment by summerspirit** [comment]
Morning!
@renrutnnej  @janl
[Beaver Bio for review](https://docs.google.com/document/d/1NDgR0ubr87qvJf4fCXNlOh1OXL46miuAKOzkl8qSrcg/edit?usp=sharing) :)

Image not included because I understand there's some big reveal secrecy around this? :D

**Comment by renrutnnej** [comment]
Hey @summerspirit! I'm reviewing now, sorry for the delay. I'll have feedback for you soon :relaxed:

**Comment by renrutnnej** [comment]
Hi @summerspirit just checking in on this bio to see how you're doing.

**Comment by summerspirit** [comment]
Hi @renrutnnej - just trying to redo it according to your feedback :)

**Comment by renrutnnej** [comment]
Hey @summerspirit just checking in to see how the draft is going ☺️

**Comment by summerspirit** [comment]
Hey @renrutnnej - was working with your feedback and I'm not making any progress on this sadly.

I have removed myself as assignee so someone better suited to the task can pick it up :)

**Comment by renrutnnej** [comment]
Oh no, I'm so sorry to hear that. No worries @summerspirit 💖

**Comment by annaboodle** [comment]
I'd love to take a stab at this! @renrutnnej

**Comment by renrutnnej** [comment]
Great @annaboodle, let me know if you need any help to get started, or if you have any questions.

**Comment by renrutnnej** [comment]
I'm working on getting this bio onto the editorial calendar so we can release this new mascot @annaboodle ☺️

**Comment by annaboodle** [comment]
@renrutnnej Wonderful!! Feel free to reach out if you'd like assistance with any future animal stories :)
