### ISSUE TITLE
CONTENT: Additional copy for hood.ie/get-help

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#67]
Part of https://github.com/hoodiehq/hood.ie/issues/234

### :octocat: Starter Issue

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :relaxed:

---

### :pencil2: The Task

In preparation for the Camp Release we are trying to update the hood.ie site. This specific writing task involves adding content to the [Hoodie “get help” page](http://hood.ie/get-help/) to flesh out the ways folks can get assistance or encouragement as they run into blockers or issues when contributing to the project.

- [x] Claim this issue (@rubymorillo)
- [x] Contact @gr2m or @janl and conduct a brief interview for context and process pointers. 
- [x] Submit to @renrutnnej @Charlotteis or @janl for review (Google docs probably work best for this sort of thing)
- [x] You are done :clap: comment below that your content is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by rubymorillo** [comment]
Hey team, I'd like to claim this issue!

**Comment by renrutnnej** [comment]
It's all yours @rubymorillo! Please let me know if you need any help to get started, or if you get stuck! ☺️

**Comment by rubymorillo** [comment]
Meeting with Gregor arranged; will get debriefed and will move forward with writing over the next few days.

**Comment by rubymorillo** [comment]
Pinging @renrutnnej! Want to take a look at the proposed [Get Help updates](https://docs.google.com/document/d/1UM5Cr467fN8HnTS21WRo2tc_62OjbQjXGE3k-GHBjOU/edit) for review? 

Notes from my convo with @gr2m and what the proposed changes were are provided in the comment above for background. Thanks!

**Comment by renrutnnej** [comment]
I just reviewed the Google doc and I think it looks perfect @rubymorillo. Thank you so much :raised_hands: 

I see the notes on encouragement above and I'm curious if you still needed direction on that since it seems somewhat vague to me here. :relaxed:

**Comment by gr2m** [comment]
added a few minor notes. I think it’s great, thanks Stephanie!

**Comment by rubymorillo** [comment]
Awesome @gr2m I updated that language!

@renrutnnej re: encouragement language; yes, I definitely need help with direction. Any tips?

**Comment by janl** [comment]
> Remove the "For Any Question You May Have" and "Learn How to Get Started" sections.

I’m curious about the reasoning for this?

I imagine `/get-help` to be a place not only for people who want to work on Hoodie, but mainly for people who are *using* Hoodie and need help.

**Comment by janl** [comment]
To clarify: I understand that we are shaping things to focus more on the *camp release*, which focusses on contributors, but I think we should have something for end-users under that URL.

**Comment by rubymorillo** [comment]
Perhaps @gr2m could better answer those questions, @janl? ^^^

**Comment by gr2m** [comment]
yeah that was me :) The FAQ is not helpful it might rather confuse at the moment, as the most new people will look into the new Hoodie. The Report a bug link eventually links to FAQ, too, and list of known bugs is also confusing. 

Maybe we can add a section back in for Hoodie users, but only tell in there that we are working on a new version, that documentation might be outdated and that the best way is to come to the chat, something like that?

**Comment by rubymorillo** [comment]
@gr2m @janl I added a ["Have questions about using Hoodie?"](https://docs.google.com/document/d/1UM5Cr467fN8HnTS21WRo2tc_62OjbQjXGE3k-GHBjOU/edit) section for end users. Let me know what you both think!

**Comment by gr2m** [comment]
We can put the `"Have questions about using Hoodie?"` first I’d say, it’s very short anyway. But this is good to publish for me either way :) Thanks @rubymorillo

**Comment by rubymorillo** [comment]
@janl done, move it up top! 
@renrutnnej it's ready to go live!

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hood.ie/pull/265 :clap:
