### ISSUE TITLE
Post Proposal: Create your own app with Hoodie’s Camp Release

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/editorial#71]
> What is your blog post about? Describe it in about one paragraph

The only way to play with the new Hoodie version is to setup https://github.com/hoodiehq/hoodie-app-tracker. But there are no real instructions on how to build your own app with the new Hoodie, and I think it would be nice to have a place where we can send people to who want to play with the latest Hoodie version. A blog post might be a great resource for that. Once it’s outdated, we can update it

> Approximately how long do you think the post will be?

I guess it will be a step-by-step kind of blog post like [this one on Starter Issues](http://hood.ie/blog/starter-issues.html)

> Approximately how long do you think it will take you to write this post?

1-2h

> Do you think your post could make use of any illustrations or photographs?

Yeah something camp related would be nice :) I guess I could reuse the tent from our [birthday newsletter](http://us4.campaign-archive2.com/?u=12d36bbe9418ed6a43127cd62&id=259aa93a0e)

> Do you have any links to previous writing?

http://hood.ie/blog/starter-issues.html

> Where else can we find you on the internet? (e.g. your blog, Tumblr, Medium, Twitter, etc.)

https://twitter.com/gr2m/

> Anything else you want to tell us?

I’m happy to work with someone else on this :)

---

**UPDATE: APRIL 5**: @gr2m will try to write the blog post next week and I'm (@rubymorillo) going to help with editing once he's done with his first draft (using Google Docs).

**Comment by rubymorillo** [comment]
Hey team, did we need help with this one at all? @gr2m @renrutnnej

**Comment by renrutnnej** [comment]
Yes  please!

**Comment by rubymorillo** [comment]
Awesome! I'll coordinate with @gr2m on this :). 

@renrutnnej do we have docs on how we create these kinds of blog posts? Does editorial typically interview and write it, or do we mainly edit the content?

**Comment by renrutnnej** [comment]
Since I've helped, we've left it up to the content creator and editorial has provided formatting help and editing. I hope that answers your question but if not, let me know!

**Comment by rubymorillo** [comment]
@gr2m ping! Just wanted to see if you had an idea about time line for writing the post for my FYI :)

**Comment by gr2m** [comment]
@rubymorillo I still have it on my list. Friday is my Hoodie day, okay to do it then?

**Comment by rubymorillo** [comment]
Yup @gr2m feel free to ping me when it's ready :)

**Comment by Raoooo** [comment]
Great information...And very helpfull for me...If you have any information about <a href="https://www.j4jacket.com/bon-jovi-captain-america-leather-jacket.html">bon jovi captain america jacket</a>
 then share please...thanks
