### ISSUE TITLE
Add Hoodie to http://pouchdb.com/users.html

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#72]
### :octocat: Starter Issue

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :relaxed:

---

### :pencil2: The Task

We need someone to create some copy (1-2 sentences) about Hoodie and submit it to the official PouchDB site (http://pouchdb.com/users.html). 

I can assist with getting assets to send along with our submission.

- [x] Claim this issue (@turcapat)
- [x] Research and write a 1-2 sentence description of what Hoodie does.
- [x] Find out the guidelines for submitting to http://pouchdb.com/users.html.
- [x] Submit to @renrutnnej @Charlotteis or @janl for review (Google docs probably work best for this sort of thing)
- [x] Ping any of the above for a logo asset to submit with the final copy. 
- [x] You are done :clap: comment below that your content is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by nickcolley** [comment]
You can find out how to contribute to the site here: https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md#building-pouchdb-documentation

Whoever claims this issue ping me if you need any help contributing to PouchDB :smile_cat:

**Comment by turcapat** [comment]
Hi, is this issue reserved for the DC meet the hoodies ? I would like to make my first PR so i am looking for some issue to solve :) I am totally new to the Hoodie, so I would appreciate any help.

**Comment by gr2m** [comment]
no it was not reserved I just added the label so it’s easier to find. It’s all yours Patrik :)

**Comment by turcapat** [comment]
Thank you very much !!! :) I am going to solve it as soon as possible.

**Comment by turcapat** [comment]
Hi guys, i just started to work on issue, i created a google doc:
https://docs.google.com/document/d/1pNLv4E7-_XQsMtIQHQwvaiT75MKFkLYwiLJx0MHQcKo/edit?usp=sharing

Could you give me some feedback ? :)  @renrutnnej,  @Charlotteis @janl

**Comment by renrutnnej** [comment]
Since it's view only I'll give my feedback here:

“Hoodie provides complete back-end solution for your front-end code. It helps you develop your web application fast, easy and accessible. Just plug in your front-end code to Hoodie API, and your app is ready.”

+ change references of `back-end` or `front-end` to `backend` and `frontend` per the [glossary guide](https://github.com/hoodiehq/editorial/wiki/Glossary-of-common-terms)
+ s/solution/solutions
+ By accessible do you mean it makes the web application accessible or using Hoodie is accessible to users? I want to be clear on this term because `accessibility` has a distinct industry connotation
+ Rephrase `Just plug your front-end code to Hoodie API...` to `Just plug your frontend code into Hoodie’s API...` to avoid confusion with __plugins__ (a feature further down the release plan) 

Thanks for writing this @turcapat :sparkling_heart: :raised_hands:

**Comment by turcapat** [comment]
Thank you for corrections, since I am not native speaker it is a big help :) With that accessibility i meant that app will be accessible, because Hoodie is Offline First. I am going to try to formulate it better.

**Comment by turcapat** [comment]
@renrutnnej Check now :) Btw. I made the document editable.

**Comment by turcapat** [comment]
What about now ? :)

**Comment by renrutnnej** [comment]
I added my tweaks, I'd just like feedback from @gr2m or @janl as well. Great stuff @turcapat :sparkles:

**Comment by turcapat** [comment]
If it is OK, you can send me logo asset. :)

**Comment by gr2m** [comment]
@turcapat looking good, added minor suggestions.

For the last sentence, instead of 

> Just plug your frontend code into Hoodie’s API, and your app is ready

I’d say

> Just plug Hoodie’s API into your frontend code, and your app is ready

As logically you add the Hoodie API to your frontend code, not the other way around. Does that make sense?

**Comment by gr2m** [comment]
@espy do you have Hoodie the logo, maybe with the domain in it?

**Comment by espy** [comment]
Here's two!

![hoodie_logo_colourful_2 0_closed_1000](https://cloud.githubusercontent.com/assets/391124/14058938/6b89b220-f330-11e5-9179-4cab9d26266b.png)

And [as SVG](https://db.tt/a1n0c0aX)

![hoodie_logo_dark_2 0_closed_1000](https://cloud.githubusercontent.com/assets/391124/14058939/6b9005a8-f330-11e5-9ed5-2e6f3507af1f.png)

And the dark one [as SVG](https://db.tt/XxiNRKUr)

And here's a [white SVG](https://db.tt/us5Fej6R), just in case.

**Comment by turcapat** [comment]
![hoodie_local](https://cloud.githubusercontent.com/assets/7606711/14059343/4d7e7de8-f33e-11e5-87d8-04c7cfbea34f.png)

Here is how it looks like localy :) any suggestions ?

**Comment by gr2m** [comment]
I think it’s great :) Maybe link the Hoodie logo to http://hood.ie, too, if you haven’t yet :)

**Comment by turcapat** [comment]
It will be my first Pull Request. Can you tell me how to I commit and push my local changes to Pouch DB repository ? Or it is like a normal git commit and push ?

**Comment by nickcolley** [comment]
Hey @turcapat 

You can check the contribution guidelines here to get started: https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md

If you fork the repository and get a merge request in I can help merge it in for you.

**Comment by turcapat** [comment]
I have read it already, but I am not really a smarter after it. I forked the repository and pull my local changes to this fork. But they say do not to use Green Button. So how do I create a Pull Request ?

**Comment by gr2m** [comment]
Yes create the pull request. The "Green Button" is about merging the pull request, not starting it. They could make that more clear :)

**Comment by nickcolley** [comment]
Woop, all merged in will be live on the site next time we deploy. (https://github.com/pouchdb/pouchdb/pull/5008)

Thanks a lot @turcapat double contribution to both Hoodie and PouchDB :) :tada: :dancer:

**Comment by turcapat** [comment]
Thank you very much guys :) I really appreciate your help :) !!

**Comment by renrutnnej** [comment]
Do you have a twitter handle @turcapat? I want to send out a tweet to congratulate you for your great work on this :relaxed:

**Comment by turcapat** [comment]
Oh I am sorry, i dont have a twitter. :)
