### ISSUE TITLE
BLOG: Meet the Hoodies – Gregor Martynus

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#74]
![welcome-to-open-source-atlanta](https://cloud.githubusercontent.com/assets/39992/13732817/58766428-e960-11e5-8496-c65891ad0835.png)

**This issue is reserved for participants of  [Welcome to Open Source, Atlanta](http://www.meetup.com/Jr-Dev-Mentoring/events/228951389/)**.
If it’s still available after April 2nd, it’s all yours :)

---

### :pencil2: The Task

We’ve started a series of brief interviews with some of the Hoodie core contributors. You can see examples of these here:

+ [Alex Feyerke](http://hood.ie/blog/Alex-Feyerke-meet-the-hoodies-1.html)
+ [Charlotte Spencer](http://hood.ie/blog/Charlotte-Spencer-meet-the-hoodies-2.html)
+ [Jenn Turner](http://hood.ie/blog/meet-the-hoodies-jenn-turner.html)  

I’m requesting that someone write up a new interview with Gregor Martynus (@gr2m). To claim this task do the following:

- [x] Claim this issue (@kmcrayton7)
- [x] Review the previous posts above. 
- [x] Find the `Meet the Hoodies` [sample doc in this repo](https://github.com/hoodiehq/editorial/blob/master/documents/meet-the-hoodies.md).
- [x] Contact @gr2m to collaborate on a draft. 
- [x] Submit to @renrutnnej @gr2m or @janl for review (Google docs probably work best for this sort of thing)
- [ ] You are done :clap: comment below that your content is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by gr2m** [comment]
@renrutnnej mind if I reserve this issue for our "Welcome to Open Source" event in Atlanta?
http://www.meetup.com/Jr-Dev-Mentoring/events/228951389/

**Comment by renrutnnej** [comment]
Not at all!

-- 
Jenn Turner
I ❤️ great email at jennwrit.es/newsletters 

On March 13, 2016 at 8:49:19 PM, Gregor Martynus (notifications@github.com) wrote:

@renrutnnej mind if I reserve this issue for our "Welcome to Open Source" event in Atlanta?
http://www.meetup.com/Jr-Dev-Mentoring/events/228951389/

**Comment by kmcrayton7** [comment]
I'm looking into this one

**Comment by renrutnnej** [comment]
Are you claiming this @kmcrayton7 :relaxed: ?

**Comment by gr2m** [comment]
oh yeah :)

**Comment by kmcrayton7** [comment]
@renrutnnej I'm working on it now.

**Comment by renrutnnej** [comment]
I left feedback on the Google doc, let me know if you need help getting the PR process going :)

**Comment by renrutnnej** [comment]
Resolved by https://github.com/hoodiehq/hood.ie/pull/274 once merged. :relaxed:

**Comment by gr2m** [comment]
@renrutnnej you can add "fixes hoodiehq/editorial#74" to the description of the pull request at hoodiehq/hood.ie#274, then this issue will be closed automagically by GitHub when the PR gets merged
