### ISSUE TITLE
BLOG: Meet the Hoodies – Julia Simplicio

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#75]
### :octocat: Starter Issue

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :relaxed:

---

### :pencil2: The Task

We’ve started a series of brief interviews with some of the Hoodie core contributors. You can see examples of these here:

+ [Alex Feyerke](http://hood.ie/blog/Alex-Feyerke-meet-the-hoodies-1.html)
+ [Charlotte Spencer](http://hood.ie/blog/Charlotte-Spencer-meet-the-hoodies-2.html)
+ [Jenn Turner](http://hood.ie/blog/meet-the-hoodies-jenn-turner.html)  

I’m requesting that someone write up a new interview with Julia Simplicio (@jsimplicio). To claim this task do the following:

- [x] Claim this issue (@pawan92)
- [x] Review the previous posts above. 
- [x] Find the `Meet the Hoodies` [sample doc in this repo](https://github.com/hoodiehq/editorial/blob/master/documents/meet-the-hoodies.md).
- [x] Contact @jsimplicio to collaborate on a draft. 
- [x] Submit to @renrutnnej @gr2m or @janl for review (Google docs probably work best for this sort of thing)
- [x] You are done :clap: comment below that your content is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by pawan92** [comment]
@renrutnnej hey jenn while i wait for my other hoodie to respond..can i do this one as well? :smile_cat:

**Comment by renrutnnej** [comment]
@pawan92 are there any other writing contributions that interest you?

**Comment by pawan92** [comment]
@renrutnnej i have looked through and am open to anything! any suggestions?

**Comment by renrutnnej** [comment]
If you still want to grab this one @pawan92 I think you should do it! 😺

**Comment by jsimplicio** [comment]
I'm usually free a couple hours every day if that helps :D

**Comment by pawan92** [comment]
@renrutnnej lol sure :grin:  @jsimplicio hey can i get you email so i can share the google docs with questions?

**Comment by jsimplicio** [comment]
@pawan92 sure you can reach me at contact@juliasimplicio.com

**Comment by pawan92** [comment]
@jsimplicio shared it with you :smile:

**Comment by pawan92** [comment]
https://docs.google.com/document/d/1P43R06CaQCX3KcGBunpWQzPsUQksEnMmBE3S5CYFOmY/edit the google docs if its easier!

**Comment by renrutnnej** [comment]
Hey @pawan92 is this ready for review?

**Comment by pawan92** [comment]
@renrutnnej i have not been able to get in touch with @jsimplicio :(

**Comment by renrutnnej** [comment]
It looks like Julia has included some great responses. @pawan92 do you want to write up a brief intro and put this into a blog post format in the site/blog repo here https://github.com/hoodiehq/hood.ie?

**Comment by pawan92** [comment]
@renrutnnej sure! im a little busy this week. but ill try to fit this in and have it to you asap! 😄
