### ISSUE TITLE
BLOG: Meet the Hoodies – Nick Hehr

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#76]
### :octocat: Starter Issue

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :relaxed:

---

### :pencil2: The Task

We’ve started a series of brief interviews with some of the Hoodie core contributors. You can see examples of these here:

+ [Alex Feyerke](http://hood.ie/blog/Alex-Feyerke-meet-the-hoodies-1.html)
+ [Charlotte Spencer](http://hood.ie/blog/Charlotte-Spencer-meet-the-hoodies-2.html)
+ [Jenn Turner](http://hood.ie/blog/meet-the-hoodies-jenn-turner.html)  

I’m requesting that someone write up a new interview with Nick Hehr (@hipsterbrown). To claim this task do the following:

- [x] Claim this issue (@pawan92)
- [ ] Review the previous posts above. 
- [ ] Find the `Meet the Hoodies` [sample doc in this repo](https://github.com/hoodiehq/editorial/blob/master/documents/meet-the-hoodies.md).
- [ ] Contact @HipsterBrown to collaborate on a draft. 
- [ ] Submit to @renrutnnej @gr2m or @janl for review (Google docs probably work best for this sort of thing)
- [ ] You are done :clap: comment below that your content is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by pawan92** [comment]
Hey is it possible for me to do this? with @HipsterBrown :smile_cat:

**Comment by renrutnnej** [comment]
Absolutely @pawan92! I'll assign it to you now. Please let me know if you have any questions or you need help to get started :relaxed:

**Comment by pawan92** [comment]
@renrutnnej awesome! so im familiar with git and working it but just to clarify i interview hipsterbrown and record her/his? (i apologize lol) answers (google docs). fork the document presumably and make changes..push and do PR? am i on the right path?

**Comment by renrutnnej** [comment]
It sounds like you're definitely on the right path @pawan92. You can use git if you're more comfortable but I think there are also instructions if you want to try the GitHub UI.

**Comment by pawan92** [comment]
I will look into it! so i forked and cloned a local copy which gives me the entire editorial folder. I will save the doc in the meet the hoodies under blog posts before i push. Is that ok? @renrutnnej

**Comment by renrutnnej** [comment]
That sounds right. Let me know if you need help @pawan92 :relaxed:

**Comment by HipsterBrown** [comment]
:wave: Hello @pawan92! Let me know when you're ready to collaborate on a draft. :smile:

**Comment by pawan92** [comment]
Hey @HipsterBrown ! can i get your email address? i have the questions on google doc which i want to share with you.

**Comment by pawan92** [comment]
@renrutnnej hey jenn created a PR with the document containing nicks answers. hope i did it right #firstPR :smile:

**Comment by renrutnnej** [comment]
I saw that @pawan92 and since it's a blog post, could you to submit following the blog post directions here: https://github.com/hoodiehq/hood.ie#blog ? I'm happy to help walk you through it. :relaxed:

**Comment by pawan92** [comment]
@renrutnnej submitted the PR. let me know. if i didnt do it right we can walk through it together :)
