### ISSUE TITLE
BLOG: Hoodie news assignment!

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#77]
On Tuesday March 15, @janl and @renrutnnej will be on a popular Open Source podcast called [FLOSS Weekly](https://twit.tv/shows/floss-weekly) to talk about Hoodie! :tada: :dog:

We need a contributor to write a brief synopsis after the show to post on the blog with the link to the podcast with maybe an epic quote from the show or something. :relaxed: 

Or especially if there are links mentioned in the show, it would be great to have a recap post with that information readily available. 

To take on this blog post:

- [x] Claim this issue (@sjnorth)
- [x] Review the FLOSS Weekly program at the link above. 
- [x] Find the instructions for posting a blog post to the [Hoodie blog](http://hood.ie/blog/) in the [`hoodiehq/hood.ie` repo here](https://github.com/hoodiehq/hood.ie#blog). 
- [x] Submit a pull request (PR) as part of the end of the blog process. 
- [x] You are done :clap: comment below that your PR is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by sjnorth** [comment]
Hi there, this one looks perfect for me. Can I grab it?

**Comment by gr2m** [comment]
Absolutely :) Welcome to Hoodie :wave:

**Comment by renrutnnej** [comment]
Welcome @sjnorth :sparkles: Please let me know if you need any help or if you get stuck. :relaxed:

**Comment by sjnorth** [comment]
Hi there, thanks for the warm welcome :) Yep, will let you know if I need anything.

**Comment by sjnorth** [comment]
Great interview! Couple of questions: 1) when do you need it ready by, 2) any particular areas you'd like me to highlight? 3) how long should the synopsis be?

**Comment by renrutnnej** [comment]
Hi @sjnorth! It would be awesome if we could publish something tomorrow. Nothing too long, maybe like 200-ish words on calling out some highlights and why people should check out the show.

Also, the podcast should be available in a couple of hours so we can embed it into the post too! :+1:

**Comment by sjnorth** [comment]
Tomorrow works! I'm in Istanbul so I've got a nice chunk of time advantage :) 
one more thing, were there any links I'd need to include?

**Comment by renrutnnej** [comment]
Probably but I’ll suggest them after you have some copy so we can figure out the best way to work them in and/or list them. Thank you so much!

-- 
Jenn Turner
I ❤️ great email at jennwrit.es/newsletters 

On March 15, 2016 at 1:59:19 PM, Samantha North (notifications@github.com) wrote:

Tomorrow works! I'm in Istanbul so I've got a nice chunk of time advantage :)
one more thing, were there any links I'd need to include?

**Comment by sjnorth** [comment]
OK, sounds fine! Until tomorrow.. :)

**Comment by gr2m** [comment]
that’s done :)
