### ISSUE TITLE
Blog post: a new kind of open source event

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/editorial#78]
Hello Editorial Team 👋

I will co-host a "Welcome to Open Source" event / workshop in Atlanta in April, and I wrote a blog post to introduce the idea behind it to the world, and also to send it out to other Open Source projects so that they can participate. I’ve started a Pull Request to our blog here:
hoodiehq/hood.ie#253

**Comment by renrutnnej** [comment]
I think this is the link here: https://github.com/hoodiehq/hood.ie/pull/253

**Comment by gr2m** [comment]
yes, thanks, fixed
