### ISSUE TITLE
Shoutouts Week 12

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/editorial#79]
Here is what I gather for the 1st shout out post. Hope you can work with it @sjnorth?

- Continuous deployment & Docker image for [Tracker app](https://github.com/hoodiehq/hoodie-app-tracker) & our [Camp tutorial](https://github.com/hoodiehq/hoodie-camp-tutorial), thanks to [Christoph](https://github.com/christophwitzko)
- Patricia hosted Offline Web Apps with Hoodie workshop at [Health Camp](http://hackinghealth.ca/event/hacking-health-camp/)
- Gem, Nick & Gregor did [Meet the Hoodies event](https://ti.to/hoodie/dc-meet-the-hoodies) in Washington DC (_TODO: [add picture](https://www.dropbox.com/sh/3gpzu0sfgpkqgsv/AAB7M58cJZKR8wU2WtXIQlCIa?dl=0)_)
- [Jay](https://github.com/JayWIlsonJr) started [his first PR](https://github.com/hoodiehq/hoodie-server-account/pull/129) during the DC event and found a bug that we missed till now. [Ola](https://github.com/Oladele) did the same and could even [fix the issue](https://github.com/hoodiehq/hoodie-server-account/pull/128) while at it. 
- Alex: various text corrections and small improvements to Camp Tutorial (https://github.com/hoodiehq/hoodie-camp-tutorial/pull/5)

- austinjreilly: first PR (https://github.com/hoodiehq/hoodie-server-account/issues/93) and first starter issue created (https://github.com/hoodiehq/hoodie-server-account/issues/122), which was done as first PR to Hoodie by [Manit Singh Kalsi](https://github.com/kazekagegaara) 
- More First PRs: [Bryan Bierce](https://github.com/bryanbierce), [Wilson Jr.](https://github.com/JayWIlsonJr), [Sebastian Pancia](https://github.com/sebbel), [Samantha North](https://github.com/sjnorth), [Tri Nguyen](https://github.com/tnguyen14?tab=activity)

- [Finn](https://github.com/finnp) – rocking it with the internal architecture migration: https://github.com/hoodiehq/hoodie/issues/458

- [Julia](https://github.com/jsimplicio) continues working on our Tracker App and got several pull request closed in the past week.

- [Ransom](https://github.com/ransomw) implemented the  `accountAdmin.sessions.add(options)` API, which will be great for debugging your apps

- [Jenn](https://github.com/renrutnnej) started the weekly Editorial Meetup: each Wednesday 9:30am EDT at https://plus.google.com/hangouts/_/neighbourhood.ie/editorial-hang

- [Cecily](https://github.com/skeskali) & [Jenn](https://github.com/renrutnnej) brought as the past TGIF posts :)

- [Sean](https://github.com/seanjohnite) found out that Hoodie’s [connectionStatus](hoodie-connection-status) API does not yet have 100% coverage, went ahead and fixed it. So much <3 

- Thanks for reviews [Stephan](https://github.com/boennemann), [Christoph](https://github.com/christophwitzko), [Nick Colley](https://github.com/nickcolley), [Nick Hehr](https://github.com/HipsterBrown), [Jan](https://github.com/janl)

- And special thanks to [Samantha](https://github.com/sjnorth) who help publishing the first episode of Hoodie’s weekly community shout outs :)

**Comment by renrutnnej** [comment]
Thank you for your work on this @gr2m and @sjnorth :sparkling_heart:

**Comment by sjnorth** [comment]
Hey Gregor

Thanks for sending this. Yep it's all fine. I will have it ready for you by
tomorrow.

Sent on the move

**Comment by renrutnnej** [comment]
Closing per http://hood.ie/blog/shoutouts-week-12.html
