### ISSUE TITLE
LinkedIn page for Hoodie

### ISSUE THREAD

**Issue by sjnorth** [hoodiehq/editorial#80]
I can't find a LinkedIn page for Hoodie. If there isn't one, shall we create it?

**Comment by renrutnnej** [comment]
Since LinkedIn is a professional networking site, I'm curious about whether there's a precedence for open source software projects to have a presence there. 

I'm going to defer to @janl and @gr2m (and the other co-creators) on this one, as I am not quite versed in the grey areas of OSS.

**Comment by gr2m** [comment]
What would be the benefit? Hoodie also has no Facebook page, I’d rather not add more channels that people can talk to us, to keep noise low.

**Comment by gr2m** [comment]
^5 @renrutnnej for posting 2s apart from each other :)

**Comment by sjnorth** [comment]
I await the final verdict with anticipation. Let me know if I can help in any way. :)

**Comment by renrutnnej** [comment]
I'm closing this per @gr2m preference in his comments above.
