### ISSUE TITLE
BLOG: Hoodie news assignment!

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#83]
On Saturday April 2, @gr2m will be [co-hosting a new type of open source event](http://www.meetup.com/Jr-Dev-Mentoring/events/228951389/) in Atlanta to introduce new contributors to Hoodie! :tada: :dog:  We featured the announcement of this event on the blog previously [here](http://hood.ie/blog/a-new-kind-of-open-source-event.html).

We need a contributor to write a brief synopsis about the event and/or take some photos if onsite. :relaxed: 

Also if there are links from mentions on Twitter or to new features/first time PRs please include those! 

To take on this blog post:

- [x] Claim this issue (`comment below to claim or assign yourself`)
- [x] Review the FLOSS Weekly program at the link above. 
- [x] Find the instructions for posting a blog post to the [Hoodie blog](http://hood.ie/blog/) in the [`hoodiehq/hood.ie` repo here](https://github.com/hoodiehq/hood.ie#blog). 
- [ ] Submit a pull request (PR) as part of the end of the blog process. 
- [ ] You are done :clap: comment below that your PR is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by gr2m** [comment]
@renrutnnej okay if @kmcrayton7 and I take this one?

**Comment by renrutnnej** [comment]
Yes please!  
  

Jenn Turner  

I &lt;3 great email [jennwrit.es/newsletters](http://jennwrit.es/newsletters
"http://jennwrit.es/newsletters" )

[@jennwrites](https://twitter.com/jennwrites)

  

On Apr 19 2016, at 4:22 pm, Gregor Martynus &lt;notifications@github.com&gt;
wrote:  

> [@renrutnnej](https://github.com/renrutnnej) okay if
[@kmcrayton7](https://github.com/kmcrayton7) and I take this one?

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/hoodieh
q/editorial/issues/83#issuecomment-212110075)![](https://github.com/notificati
ons/beacon/ACdpFRzTWLBGnrEgMqvUYlRy1SP4FKkcks5p5TmMgaJpZM4H-MAd.gif)

**Comment by renrutnnej** [comment]
I don't know how newsworthy this is at this point? What do you think @gr2m @kmcrayton7?

**Comment by renrutnnej** [comment]
Closing this since it's been 30 days and no one responded within the 72 hour window that it was still relevant to publish.
