### ISSUE TITLE
EDIT: Hoodie Tutorial #2

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#84]
![welcome-to-open-source-atlanta](https://raw.githubusercontent.com/welcome-to-open-source/Atlanta/master/assets/banner.png)

**This issue is reserved for participants of [Welcome to Open Source, Atlanta](http://www.meetup.com/Jr-Dev-Mentoring/events/228951389/)**.

If it’s still available after April 2nd, it’s all yours :)

---

### :octocat: Starter Issue

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :relaxed:

---

### :pencil2: The Task

We have a series of tutorials that need to be reviewed for typos, markdown errors and general clarity. 

This issue is to review [Getting started with Hoodie - Part 2](http://docs.hood.ie/en/tutorials/).

- [x] Claim this issue (@raquelxmoss )
- [x] Review the page above: [Getting Started with Hoodie - Part 2](http://docs.hood.ie/en/tutorials/). 
- [x] Find the `index.md` file in the `tutorials/documentation` folder of the documentation repository [here](https://github.com/hoodiehq/documentation/blob/gh-pages/en/tutorials/index.md).
- [x] Confirm that the tutorial follows the [style guide](https://github.com/hoodiehq/editorial/wiki/Hoodie-Language-Style-Guide) and [glossary of terms](https://github.com/hoodiehq/editorial/wiki/Glossary-of-common-terms) from the wiki.
- [x] Click the pen icon at right to edit, or at least begin the option to create your own “patch” for fixes.

<img width="338" alt="screen shot 2016-04-02 at 12 17 38 am" src="https://cloud.githubusercontent.com/assets/2582805/14224397/73c22a0c-f868-11e5-80d8-f8af7e1af582.png">

- [x] Submit your patch to be merged (or if possible, edits to master). 
- [ ] You are done :clap: comment below that your content is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by raquelxmoss** [comment]
Hello! I'd like to take claim this issue.

**Comment by raquelxmoss** [comment]
Hello! I'd like to claim this issue :smile:

**Comment by finnp** [comment]
@raquelxmoss Hey :) It's all yours. Let us know if you have any questions.

**Comment by raquelxmoss** [comment]
@finnp This is [ready for review](https://github.com/hoodiehq/documentation/pull/206) :smiley:

**Comment by renrutnnej** [comment]
Edits made and pushed live via https://github.com/hoodiehq/documentation/pull/206
