### ISSUE TITLE
EDIT: Map app tutorial

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#85]
### :octocat: Starter Issue

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :relaxed:

---

### :pencil2: The Task

We have a series of tutorials that need to be reviewed for typos, markdown errors and general clarity. 

This issue is to review [How to Build a Map App with Hoodie](http://docs.hood.ie/en/tutorials/map-app.html).

- [ ] Claim this issue (comment below)
- [ ] Review the page above: [How to Build a Map App with Hoodie](http://docs.hood.ie/en/tutorials/map-app.html)
- [ ] Find the `map-app.md` file in the `tutorials/documentation` folder of the documentation repository [here](https://github.com/hoodiehq/documentation/blob/gh-pages/en/tutorials/map-app.md).
- [ ] Confirm that the tutorial follows the [style guide](https://github.com/hoodiehq/editorial/wiki/Hoodie-Language-Style-Guide) and [glossary of terms](https://github.com/hoodiehq/editorial/wiki/Glossary-of-common-terms) from the wiki.
- [ ] Click the pen icon at right to edit, or at least begin the option to create your own “patch” for fixes.

<img width="338" alt="screen shot 2016-04-02 at 12 17 38 am" src="https://cloud.githubusercontent.com/assets/2582805/14224397/73c22a0c-f868-11e5-80d8-f8af7e1af582.png">

- [ ] Submit your patch to be merged (or if possible, edits to master). 
- [ ] You are done :clap: comment below that your content is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by kprenesti** [comment]
I'm looking into this one.

**Comment by renrutnnej** [comment]
Thanks @kprenesti, I've assigned you just now. Let me know if there's anything I can do to help out :relaxed:

**Comment by gr2m** [comment]
Happy to help too if there are any technical questions :)

**Comment by gr2m** [comment]
Hey @kprenesti do you still want to work on this?

**Comment by renrutnnej** [comment]
Creating new starter issues to replace this one
