### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by janl** [hoodiehq/editorial#9]
This issues is the first follow-up from the first call we had on November 21st.

The group decided to tackle one small project first to figure out the rest of the process.

The project is: **Meet The Hoodies.**

Here is the rough idea:

Meet The Hoodies (sing a long to [the melody :notes: of Wheel of Fortune](https://www.youtube.com/watch?v=2f7qAY1PztI)) is a blog series that in each episode celebrates one of the Hoodie community members. Each edition has a somewhat fixed format with maybe three to five questions that everybody gets, along with a photo or any other desired imagery for the person.

## The Issue

Right now, there is no plan to run the Meet the Hoodies series. We’d like to change that.

## The Solution

Here’s a rough outline of which tasks are needed.

1. Document Meet the Hoodies format, including questions to ask and everything.
2. Divide the production of one episode of Meet the Hoodies into sub-tasks (these are just suggestions, feel free to make your own list):
  - finding a person
  - defining the interview questions
  - coordinating with the interviewee to get answers and a photo or other image
  - review the questions and answers for content and style
  - copy-editing the questions and answers
  - formatting the answers to look like a blog post post
  - creating a pull request to the blog
  - publish the post
  - send tweets about the new post in three or four time-zones around the globe
3. Put the sub-tasks on a schedule.
4. Have people assign themselves to the sub-tasks.
5. Ship! :ship:

Some of this isn’t well-defined yet, and we’ll all work together to figure it out. For example: where do we write down the schedule? I don’t know, maybe this issue, maybe in the wiki. Where do we track the sub-tasks? I’d say we use GitHub issues here for this, but maybe you have a better idea.

## When is the issue considered complete

When there is at least one Meet the Hoodies post on the blog and when we have documented the process on how we got there.

Bonus points for having one more more in the pipeline by then.

**Comment by schisepo** [comment]
@janl - I'd like to begin documenting a format for "Meet the Hoodies". Question - Do I create the format as  new issue or do I create a document like meet-the-hoodies-format.md? I'm still finding my way around here and I think I would get it quicker if I actually put something in.

**Comment by schisepo** [comment]
@janl I've adopted the [Blog Process](/hoodiehq/editorial/blob/master/documents/blog-process.md) documented by @remixz and kicked off the Meet the Hoodies series by submitting a pitch proposal using this ->  [Pitch Template](/hoodiehq/editorial/blob/master/documents/pitch-template.md) 

The next step should be a review by the editorial team members. The proposal is issue #14

**Comment by bnb** [comment]
So just a small commentary on location of the sub-tasks, at nodejs/evangelism we have a weekly issue that is posted titled along the lines of "Weekly update - week of Jul 7 - 13". It's a good structure, and keeps it 100% visible - all content is handled through issues, so people will see it when looking at the repo anyway. I highly suggest this kind of format for recurring content.

**Comment by janl** [comment]
This looks all good to me, can we close this as we now have a post online, another one in the making and a documented process?

**Comment by Charlotteis** [comment]
I'm happy to close this. As always, we can re-open it if we need to :)
