### ISSUE TITLE
NEWS: Hoodies at JSConf Budapest

### ISSUE THREAD

**Issue by renrutnnej** [hoodiehq/editorial#91]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). 

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### 🤔 What you will need to know

English, knowledge of markdown isn't necessary but it helps. ☺️ 

### 🐞 The Issue

The Hoodies (Jan, Lena, Nick, Nolan) were just at JSConf Budapest this week and we need to write a blog post about the event! 

We need a contributor to write a brief synopsis about the event and/or gather some photos of the event. :relaxed: 

Also if there are links from mentions on Twitter (from talks or workshops) please include those! 

To take on this blog post:

- [x] Claim this issue: @pawan92 
- [x] Compose a blog post about the event
- [x] Find the instructions for posting a blog post to the [Hoodie blog](http://hood.ie/blog/) in the [`hoodiehq/hood.ie` repo here](https://github.com/hoodiehq/hood.ie#blog). 
- [x] Submit a pull request (PR) as part of the end of the blog process: https://github.com/hoodiehq/hood.ie/pull/306
- [x] You are done :clap: comment below that your PR is ready for review :tada:

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by pawan92** [comment]
Hey @renrutnnej ill be working on this issue. ill see if i can find information regarding this topic online and if you have any resources that would be welcome as well!

**Comment by renrutnnej** [comment]
See https://github.com/hoodiehq/hood.ie/issues/306 for explanation.
